### PR TITLE
Pass errors to client. Use Exception constructor to provide error message

### PR DESCRIPTION
**Pull request by owl-from-hogvarts**
This PR implements changes, proposed in linked trello cards

### CODE REVIEW

**Comment by owl-from-hogvarts** [comment]
[Report server errors to client](https://trello.com/c/7MEptRgq/66-report-server-errors-to-client)

**Comment by owl-from-hogvarts** [comment]
[Rework errors](https://trello.com/c/08WdYZq4/74-rework-errors)

**Comment by owl-from-hogvarts** [comment]
[Gracefully handle unparsable responses](https://trello.com/c/dEfobrew/68-gracefully-handle-unparsable-responses)

**Comment by owl-from-hogvarts** [comment]
[Improve global error handler](https://trello.com/c/WflDRCEg/73-improve-global-error-handler)

**Review by BIZHAN28 — APPROVED** [review]
Everything is OK

**Pull request closed without merging**
